### ISSUE TITLE
ARMS Demo Ore Scanner StackOverflow when it attempts to land

### ISSUE THREAD

**Issue by jjtParadox** [Rynchodon/ARMS#121]
The Ore Scanner drone in the [ARMS Demo world](http://steamcommunity.com/sharedfiles/filedetails/?id=632399714) causes a freeze and crash when it switches from moving toward the coordinate to landing on the asteroid. This occured using SpaceEngineers stable, LoadARMS v0.4 and ARMS Debug built from the repo today (11/2/2016).

[ARMS-log-0.txt](https://github.com/Rynchodon/ARMS/files/567840/log-0.txt)
[SpaceEngineers.txt](https://github.com/Rynchodon/ARMS/files/567851/SpaceEngineers.txt)

**Comment by jjtParadox** [comment]
Also of note is that the solar panels of the demo world tend to wobble due to the "main" rotor wobbling (turning off that rotor stops the wobble), and sometimes if a drone is not moving when autopilot is enabled it will not activate thrusters to move.

**Comment by jjtParadox** [comment]
Just had another crash, this time not with the ore scanner. I had many of the demo world drones running, so I don't know which one caused it. SE log doesn't show anything conclusive.

Log trimmed to last 10MB:
[log-0.txt](https://github.com/Rynchodon/ARMS/files/567895/log-0.txt)

**Comment by jjtParadox** [comment]
I also believe the ore scanner was working last week before the v0.3 LoadARMS update, but I can't confirm that.

**Comment by Rynchodon** [comment]
>Also of note is that the solar panels of the demo world tend to wobble due to the "main" rotor wobbling (turning off that rotor stops the wobble)

It's due to the torque being set too high, I'll update the world in the workshop.

> and sometimes if a drone is not moving when autopilot is enabled it will not activate thrusters to move.

It happens when "Control Thrusters" is turned off, ARMS will enable the switch but the game doesn't active the thrusters for some reason.

**Comment by jjtParadox** [comment]
Thanks for the quick update! Great mod :)
